<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Player;
use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function getAvailableGames(Player $player, $rank)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('g')
            ->from('AppBundle:Game', 'g')
            ->where('g.isFinished = false')
            ->andWhere('g.rank = :rank')
            ->andWhere('g.playerTwo is null')
            ->andWhere('g.playerOne <> :one')
            ->orderBy('g.id', 'desc')
            ->setParameter('rank', $rank)
            ->setParameter('one', $player->getId())
            //->setFirstResult(0)
            //->setMaxResults(10)
        ;

        $query = $queryBuilder->getQuery();
        $result = $query->getResult();

        return $result;
    }

    public function findAGameToJoin($id, Player $player)
    {
        $queryBuilder = $this->getEntityManager()->createQueryBuilder()
            ->select('g')
            ->from('AppBundle:Game', 'g')
            ->where('g.id = :id')
            ->andWhere('g.isFinished = false')
            ->andWhere('g.rank = :rank')
            ->andWhere('g.playerTwo is null')
            ->andWhere('g.playerOne <> :one')
            ->orderBy('g.id', 'desc')
            ->setParameter('id', $id)
            ->setParameter('rank', $player->getRank())
            ->setParameter('one', $player->getId())
        ;

        $query = $queryBuilder->getQuery();
        $result = $query->getOneOrNullResult();

        return $result;

    }

}
