# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    api.exception_controller:
        class: ApiBundle\Exception\ApiExceptionController
        arguments: ['@twig', '%kernel.debug%']